import {puzzleFor,score} from '../lib/keycode';
const $=(id:string)=>document.getElementById(id)!;
const names=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
const date=new Date().toISOString().slice(0,10),target=puzzleFor(date),key='keycode-v1-'+date;
let guesses:number[][]=[],current:number[]=[],hints=0,selected=0,noteNames=false,busy=false;
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&Array.isArray(saved.guesses)&&saved.guesses.length<=6&&saved.guesses.every((g:unknown)=>Array.isArray(g)&&g.length===4&&new Set(g).size===4&&g.every(n=>Number.isInteger(n)&&n>=0&&n<12))){guesses=saved.guesses;hints=Math.min(2,Math.max(0,Number(saved.hints)||0));}}catch{}
const won=()=>guesses.some(g=>g.every((n,i)=>n===target[i]));const over=()=>won()||guesses.length===6;
function save(){try{localStorage.setItem(key,JSON.stringify({guesses,hints}));}catch{}}
function label(n:number){return noteNames?names[n]:String(n+1);}
function status(s:string){$('status').textContent=s;}
let audio:AudioContext|undefined;
async function ready(){audio??=new AudioContext();if(audio.state!=='running')await audio.resume();return audio;}
function tone(ctx:AudioContext,n:number,time:number,duration=.42,volume=.16){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='triangle';osc.frequency.value=261.625565*Math.pow(2,n/12);gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(volume,time+.015);gain.gain.exponentialRampToValueAtTime(.001,time+duration);osc.connect(gain);gain.connect(ctx.destination);osc.start(time);osc.stop(time+duration+.05);}
async function play(notes:number[],arranged=false){if(busy)return;busy=true;renderControls();try{const ctx=await ready(),start=ctx.currentTime+.05;notes.forEach((n,i)=>{if(n>=0)tone(ctx,n,start+i*.53);});if(arranged){[0,1,2,3].forEach(i=>{tone(ctx,target[0]-12,start+i*.53,.48,.10);tone(ctx,target[0]+7-12,start+i*.53,.45,.045);});}await new Promise(r=>setTimeout(r,notes.length*530+300));}catch{status('Sound could not start. Try Listen again, or keep playing with the visual clues.');}finally{busy=false;renderControls();}}
function renderControls(){document.querySelectorAll<HTMLButtonElement>('.note').forEach(b=>b.disabled=busy);($('listen') as HTMLButtonElement).disabled=busy;($('compare') as HTMLButtonElement).disabled=busy||current.length!==4;($('erase') as HTMLButtonElement).disabled=!current.length;($('submit') as HTMLButtonElement).disabled=busy||current.length!==4;($('celebrate') as HTMLButtonElement).disabled=busy;}
function render(){const board=$('board');board.replaceChildren();for(let row=0;row<6;row++){const el=document.createElement('div');el.className='guess-row';el.setAttribute('aria-label',`Guess ${row+1}`);const vals=guesses[row]||(row===guesses.length?current:[]);const scores=guesses[row]?score(vals,target):[];for(let col=0;col<4;col++){const editable=row===guesses.length&&!over(),tile=document.createElement(editable?'button':'div'),n=vals[col],s=scores[col];tile.className='tile'+(n!==undefined?' filled':'')+(s?' '+s:'')+(editable&&col===selected?' selected':'');tile.textContent=n!==undefined?label(n):'';tile.setAttribute('aria-label',`Position ${col+1}: ${n===undefined?'empty':label(n)}${s?', '+{exact:'right place',present:'other place',absent:'not used'}[s]:''}`);if(s){const badge=document.createElement('b');badge.textContent={exact:'✓',present:'↔',absent:'×'}[s];tile.append(badge);}if(editable)tile.addEventListener('click',()=>{selected=Math.min(col,current.length);render();});el.append(tile);}board.append(el);}
$('keys').replaceChildren();for(let n=0;n<12;n++){const button=document.createElement('button');button.className='note'+([1,3,6,8,10].includes(n)?' sharp':'');button.textContent=label(n);button.setAttribute('aria-label',`Add note ${label(n)}`);button.onclick=()=>add(n);$('keys').append(button);}
$('composer').hidden=over();$('result').hidden=!over();$('prompt').textContent=`Guess ${guesses.length+1} of 6`;
if(over()){$('result-title').textContent=won()?'You found the melody.':'A new melody tomorrow.';$('result-copy').textContent=(won()?`Solved in ${guesses.length} of 6 guesses. `:'The notes were '+target.map(label).join(' · ')+'. ')+(hints?`${hints} clue${hints===1?'':'s'} used. `:'')+'Come back for the next daily puzzle.';}
$('hint').hidden=over()||hints===2;$('hint').textContent=hints?'Get a higher / lower clue':'Need a clue?';renderHint();renderControls();}
function add(n:number){if(over())return;if(current.includes(n)&&current[selected]!==n){status('Each note appears once. Try a different note.');return;}if(current.length===4&&selected>=4){status('Tap a tile in your guess to replace it.');return;}current[selected]=n;selected=Math.min(selected+1,3);ready().then(ctx=>tone(ctx,n,ctx.currentTime)).catch(()=>status('Audio is unavailable. You can still use the visual clues.'));render();status(current.length===4?'Listen to both melodies, or check your guess.':'Keep going — choose four different notes.');}
function renderHint(){$('hint-copy').hidden=!hints;let text='Melody shape: '+target.slice(1).map((n,i)=>n>target[i]?'↗ up':'↘ down').join(' · ')+'.';if(hints===2){const last=guesses.at(-1);text+=' '+(last?last.map((n,i)=>`Note ${i+1}: ${n===target[i]?'correct':n<target[i]?'go higher':'go lower'}`).join(' · '):'Check a guess to see higher / lower guidance here.');}$('hint-copy').textContent=text;}
$('listen').onclick=()=>{status('Listening to the secret melody.');play(target);};
$('compare').onclick=()=>{status('Secret first. A pause. Then your guess.');play([...target,-100,...current]);};
$('erase').onclick=()=>{current.pop();selected=Math.min(current.length,3);render();};
$('submit').onclick=()=>{if(current.length!==4||over())return;guesses.push([...current]);current=[];selected=0;save();render();status(won()?'Nicely done. That melody is yours.':over()?'Listen to the answer, and try again tomorrow.':'Clues are in. Build your next guess.');if(won())play(target,true);};
$('names').onchange=()=>{noteNames=($('names') as HTMLInputElement).checked;render();};
$('hint').onclick=()=>{hints=Math.min(2,hints+1);save();render();status('Clue revealed. Using clues is part of learning.');};
$('celebrate').onclick=()=>play(target,true);
$('share').onclick=async()=>{const text=`Keycode · ${date}\n${won()?guesses.length:'X'}/6 · ${hints} clues\n`+guesses.map(g=>score(g,target).map(s=>({exact:'🟩',present:'🟨',absent:'⬜'})[s]).join('')).join('\n')+'\nhttps://notebrewer.com/play/keycode/';try{await navigator.clipboard.writeText(text);status('Result copied. The melody stays a secret.');}catch{const field=$('share-text') as HTMLTextAreaElement;field.hidden=false;field.value=text;field.select();status('Select and copy your result below.');}};
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||(e.target instanceof HTMLElement&&['INPUT','TEXTAREA','SUMMARY','BUTTON'].includes(e.target.tagName)))return;const index=['a','s','d','f','g','h','j','k','l',';',"'",']'].indexOf(e.key.toLowerCase());if(index>=0){e.preventDefault();add(index);}else if(e.key==='Backspace'){e.preventDefault();$('erase').click();}else if(e.key==='Enter'){$('submit').click();}});
$('day').textContent=new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});render();if(over())status(won()?'Today’s melody is solved. Come back tomorrow.':'Today’s puzzle is complete. A new melody arrives tomorrow.');
